language: java
install: cd spark-knn-graphs && mvn --quiet install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
script: mvn test -Dmaven.javadoc.skip=true -DargLine="-Xmx2G"

#after_success:
#  - cd spark-knn-graphs && mvn cobertura:cobertura coveralls:report
